{ pkgs }:
{
  copy-on-select = "clipboard";
  window-decoration = false;
  font-size = 18;
  font-thicken = true;
  font-feature = "-calt";
  command = "${pkgs.lib.getExe pkgs.fish}";

  window-colorspace = "display-p3";

  # Scheme: Gruber
  # Generated by Ghostty Base16 Converter
  background = "181818";
  foreground = "d8d8d8";

  selection-background = "d8d8d8";
  selection-foreground = "181818";

  palette = [
    "0=#181818"
    "1=#ab4642"
    "2=#a1b56c"
    "3=#f7ca88"
    "4=#7cafc2"
    "5=#ba8baf"
    "6=#86c1b9"
    "7=#d8d8d8"
    "8=#585858"
    "9=#ab4642"
    "10=#a1b56c"
    "11=#f7ca88"
    "12=#7cafc2"
    "13=#ba8baf"
    "14=#86c1b9"
    "15=#b5bfe2"
  ];

  keybind = "shift+enter=text:\\n";

}
